plugins:
  control_kubernetes:
    executor: host_agent
    source: https://github.com/kim135797531/cloudify-controls-kubernetes-plugin/archive/master.zip
    package_name: cloudify-controls-kubernetes-plugin
    package_version: '0.1'


